[mypy]
python_version = 3.10
strict = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
no_implicit_optional = True

[mypy-PySide6.*]
ignore_missing_imports = True

[mypy-pyqtgraph.*]
ignore_missing_imports = True

[mypy-simpleeval.*]
ignore_missing_imports = True

[mypy-weasyprint.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True




