name: Release
'on':
  push:
    tags:
    - v*
jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        pip install pyinstaller'
    - name: Build executable
      run: pyinstaller VirtualChemLab.spec
    - name: Create ZIP package
      run: Compress-Archive -Path dist/VirtualChemLab/* -DestinationPath VirtualChemLab-${{
        github.ref_name }}.zip
      shell: pwsh
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: VirtualChemLab-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
